"""Built-in PBN spin-trapping component library and model presets."""

from __future__ import annotations

from .spin_models import Nucleus, SpinComponent


def default_components() -> dict[str, SpinComponent]:
    comps = {
        "organic_radical_singlet": SpinComponent(
            component_id="organic_radical_singlet",
            display_name="Generic organic radical singlet",
            radical_assignment="organic radical",
            category="general organic",
            g=2.0023,
            g_bounds=(1.9980, 2.0080),
            nuclei=[],
            linewidth_mT=0.18,
            linewidth_bounds=(0.03, 2.00),
            eta=0.45,
            weight=0.5,
            interpretation="Single-line carbon/organic radical approximation.",
        ),
        "carbon_centered_h": SpinComponent(
            component_id="carbon_centered_h",
            display_name="Carbon-centered radical with beta-H",
            radical_assignment="C-centered radical",
            category="general organic",
            g=2.0026,
            g_bounds=(1.9990, 2.0080),
            nuclei=[Nucleus(isotope="1H", A_mT=1.80, label="beta H", bounds=(0.05, 4.00))],
            linewidth_mT=0.12,
            linewidth_bounds=(0.03, 1.00),
            eta=0.45,
            weight=0.3,
            interpretation="Generic beta-proton-coupled carbon radical.",
        ),
        "semiquinone_radical": SpinComponent(
            component_id="semiquinone_radical",
            display_name="Semiquinone/phenoxyl radical",
            radical_assignment="semiquinone or phenoxyl",
            category="organic/ROS",
            g=2.0046,
            g_bounds=(2.0020, 2.0075),
            nuclei=[Nucleus(isotope="1H", A_mT=0.22, label="ring H", bounds=(0.00, 0.80))],
            linewidth_mT=0.10,
            linewidth_bounds=(0.03, 0.80),
            eta=0.40,
            weight=0.3,
            interpretation="Generic oxygenated aromatic radical model.",
        ),
        "nitroxide_14n": SpinComponent(
            component_id="nitroxide_14n",
            display_name="Generic nitroxide 14N triplet",
            radical_assignment="nitroxide",
            category="nitroxide/spin label",
            g=2.0060,
            g_bounds=(2.0020, 2.0090),
            nuclei=[Nucleus(isotope="14N", A_mT=1.55, label="nitroxide N", bounds=(1.20, 2.00))],
            linewidth_mT=0.10,
            linewidth_bounds=(0.03, 0.80),
            eta=0.45,
            weight=0.5,
            interpretation="General isotropic nitroxide triplet model.",
        ),
        "nitroxide_15n": SpinComponent(
            component_id="nitroxide_15n",
            display_name="Generic 15N nitroxide doublet",
            radical_assignment="15N nitroxide",
            category="nitroxide/spin label",
            g=2.0060,
            g_bounds=(2.0020, 2.0090),
            nuclei=[Nucleus(isotope="15N", A_mT=2.15, label="nitroxide 15N", bounds=(1.60, 2.80))],
            linewidth_mT=0.10,
            linewidth_bounds=(0.03, 0.80),
            eta=0.45,
            weight=0.4,
            interpretation="General isotropic 15N nitroxide doublet model.",
        ),
        "triphenylmethyl_trityl": SpinComponent(
            component_id="triphenylmethyl_trityl",
            display_name="Trityl/TAM narrow radical",
            radical_assignment="trityl/TAM",
            category="spin probe",
            g=2.0030,
            g_bounds=(2.0000, 2.0065),
            nuclei=[],
            linewidth_mT=0.035,
            linewidth_bounds=(0.01, 0.30),
            eta=0.35,
            weight=0.3,
            interpretation="Narrow single-line trityl/TAM-like spin probe approximation.",
        ),
        "cu2_isotropic": SpinComponent(
            component_id="cu2_isotropic",
            display_name="Cu(II) isotropic hyperfine",
            radical_assignment="Cu(II)",
            category="transition metal",
            g=2.0800,
            g_bounds=(2.0000, 2.3500),
            nuclei=[Nucleus(isotope="63Cu", A_mT=8.50, label="63Cu", bounds=(1.00, 20.00))],
            linewidth_mT=0.80,
            linewidth_bounds=(0.10, 8.00),
            eta=0.65,
            weight=0.3,
            interpretation="Approximate isotropic Cu(II) quartet; anisotropic spectra require specialized analysis.",
            warning="High-field isotropic approximation; do not over-interpret anisotropic g/A tensors.",
        ),
        "mn2_sixline": SpinComponent(
            component_id="mn2_sixline",
            display_name="Mn(II) six-line marker",
            radical_assignment="Mn(II)",
            category="transition metal",
            g=2.0000,
            g_bounds=(1.9900, 2.0200),
            nuclei=[Nucleus(isotope="55Mn", A_mT=9.40, label="55Mn", bounds=(5.00, 12.50))],
            linewidth_mT=0.35,
            linewidth_bounds=(0.05, 3.00),
            eta=0.55,
            weight=0.2,
            interpretation="Common Mn(II) sextet approximation.",
        ),
        "vo2_vanadyl": SpinComponent(
            component_id="vo2_vanadyl",
            display_name="VO2+/vanadyl 51V pattern",
            radical_assignment="VO2+ / V(IV)",
            category="transition metal",
            g=1.9800,
            g_bounds=(1.9200, 2.0200),
            nuclei=[Nucleus(isotope="51V", A_mT=10.50, label="51V", bounds=(5.00, 18.00))],
            linewidth_mT=0.45,
            linewidth_bounds=(0.05, 4.00),
            eta=0.55,
            weight=0.2,
            interpretation="Approximate isotropic vanadyl/V(IV) eight-line pattern.",
            warning="Powder vanadyl spectra are often anisotropic; use this as a screening model.",
        ),
        "defect_broad_general": SpinComponent(
            component_id="defect_broad_general",
            display_name="Generic broad defect/trapped-electron background",
            radical_assignment="defect / trapped electron",
            category="solid defect",
            g=2.0030,
            g_bounds=(1.9500, 2.1500),
            nuclei=[],
            linewidth_mT=2.00,
            linewidth_bounds=(0.20, 20.00),
            eta=0.70,
            weight=0.3,
            interpretation="Broad solid-state defect, trapped-electron, or unresolved radical envelope.",
        ),
        "ov_broad_background": SpinComponent(
            component_id="ov_broad_background",
            display_name="Pd-Ov-Bi2MoO6 defect/Ov background",
            radical_assignment="defect / trapped electron",
            category="catalyst background",
            g=2.0030,
            g_bounds=(2.0000, 2.0060),
            nuclei=[],
            linewidth_mT=0.80,
            linewidth_bounds=(0.30, 2.50),
            eta=0.65,
            weight=0.2,
            interpretation="Broad oxygen-vacancy/trapped-electron background; not a PBN spin adduct.",
        ),
        "pbn_oh": SpinComponent(
            component_id="pbn_oh",
            display_name="PBN-OH / water oxidation radical",
            radical_assignment="PBN-OH",
            category="water/ROS",
            g=2.0055,
            nuclei=[
                Nucleus(isotope="14N", A_mT=1.50, label="PBN N", bounds=(1.35, 1.65)),
                Nucleus(isotope="1H", A_mT=0.30, label="beta H", bounds=(0.15, 0.45)),
            ],
            linewidth_mT=0.08,
            linewidth_bounds=(0.03, 0.25),
            interpretation="Hydroxyl/water oxidation radical; not N2RR proof.",
        ),
        "pbn_ch3_dmso": SpinComponent(
            component_id="pbn_ch3_dmso",
            display_name="PBN-CH3 / DMSO-derived carbon radical",
            radical_assignment="PBN-CH3",
            category="DMSO artifact",
            g=2.0056,
            nuclei=[
                Nucleus(isotope="14N", A_mT=1.55, label="PBN N", bounds=(1.40, 1.70)),
                Nucleus(isotope="1H", A_mT=0.28, label="beta H", bounds=(0.15, 0.45)),
            ],
            linewidth_mT=0.08,
            linewidth_bounds=(0.03, 0.25),
            interpretation="DMSO-derived carbon radical; mandatory because PBN is in DMSO.",
            warning="Always compare this before assigning N-associated candidates.",
        ),
        "pbn_ooh_o2minus": SpinComponent(
            component_id="pbn_ooh_o2minus",
            display_name="PBN-OOH / PBN-O2-",
            radical_assignment="PBN-OOH/O2-",
            category="oxygen contamination",
            g=2.0055,
            nuclei=[
                Nucleus(isotope="14N", A_mT=1.49, label="PBN N", bounds=(1.35, 1.65)),
                Nucleus(isotope="1H", A_mT=0.43, label="beta H", bounds=(0.25, 0.60)),
            ],
            linewidth_mT=0.10,
            linewidth_bounds=(0.04, 0.30),
            interpretation="Oxygen contamination / superoxide / hydroperoxyl.",
        ),
        "pbn_nnh_candidate": SpinComponent(
            component_id="pbn_nnh_candidate",
            display_name="PBN-NNH candidate",
            radical_assignment="PBN-NNH candidate",
            category="N2RR candidate",
            g=2.0055,
            nuclei=[
                Nucleus(isotope="14N", A_mT=1.45, label="PBN N", bounds=(1.30, 1.65)),
                Nucleus(isotope="1H", A_mT=0.25, label="beta H", bounds=(0.10, 0.45)),
                Nucleus(isotope="14N", A_mT=0.18, label="proximal N", bounds=(0.02, 0.35)),
                Nucleus(isotope="14N", A_mT=0.06, label="distal N", bounds=(0.00, 0.18)),
                Nucleus(isotope="1H", A_mT=0.08, label="N-H", bounds=(0.00, 0.20)),
            ],
            linewidth_mT=0.09,
            linewidth_bounds=(0.04, 0.30),
            interpretation="Candidate early N2 activation/hydrogenation radical.",
            warning="Use only as support after controls and DMSO models are evaluated.",
        ),
        "pbn_nh2_candidate": SpinComponent(
            component_id="pbn_nh2_candidate",
            display_name="PBN-NH2 candidate",
            radical_assignment="PBN-NH2 candidate",
            category="N2RR candidate",
            g=2.0055,
            nuclei=[
                Nucleus(isotope="14N", A_mT=1.45, label="PBN N", bounds=(1.30, 1.65)),
                Nucleus(isotope="1H", A_mT=0.25, label="beta H", bounds=(0.10, 0.45)),
                Nucleus(isotope="14N", A_mT=0.25, label="NH2 N", bounds=(0.05, 0.45)),
                Nucleus(isotope="1H", A_mT=0.10, label="NH H1", bounds=(0.00, 0.25)),
                Nucleus(isotope="1H", A_mT=0.10, label="NH H2", bounds=(0.00, 0.25)),
            ],
            linewidth_mT=0.09,
            linewidth_bounds=(0.04, 0.30),
            interpretation="Candidate late NHx/N2RR radical.",
            warning="Use only as support after controls and DMSO models are evaluated.",
        ),
        "pbn_nhnh_candidate": SpinComponent(
            component_id="pbn_nhnh_candidate",
            display_name="PBN-NHNH / diazene-like candidate",
            radical_assignment="PBN-NHNH candidate",
            category="N2RR candidate",
            g=2.0055,
            nuclei=[
                Nucleus(isotope="14N", A_mT=1.45, label="PBN N", bounds=(1.30, 1.65)),
                Nucleus(isotope="1H", A_mT=0.25, label="beta H", bounds=(0.10, 0.45)),
                Nucleus(isotope="14N", A_mT=0.12, label="N1", bounds=(0.00, 0.30)),
                Nucleus(isotope="14N", A_mT=0.12, label="N2", bounds=(0.00, 0.30)),
                Nucleus(isotope="1H", A_mT=0.07, label="NH H1", bounds=(0.00, 0.20)),
                Nucleus(isotope="1H", A_mT=0.07, label="NH H2", bounds=(0.00, 0.20)),
            ],
            linewidth_mT=0.09,
            linewidth_bounds=(0.04, 0.30),
            interpretation="Candidate diazene-like N2RR radical; high overfitting risk.",
            warning="High parameter count; controls are essential.",
        ),
    }
    return comps


MODEL_PRESETS: dict[str, list[str]] = {
    "G0_single_line": ["organic_radical_singlet"],
    "G1_organic_radicals": ["organic_radical_singlet", "carbon_centered_h", "semiquinone_radical"],
    "G2_nitroxide_spin_label": ["nitroxide_14n", "nitroxide_15n", "triphenylmethyl_trityl"],
    "G3_ros_spin_trap_general": ["organic_radical_singlet", "nitroxide_14n", "semiquinone_radical"],
    "G4_transition_metal_screen": ["cu2_isotropic", "mn2_sixline", "vo2_vanadyl"],
    "G5_defect_plus_radical": ["defect_broad_general", "organic_radical_singlet", "semiquinone_radical"],
    "M0_defect_only": ["ov_broad_background"],
    "M1_water_dmso": ["ov_broad_background", "pbn_oh", "pbn_ch3_dmso"],
    "M2_water_dmso_o2": ["ov_broad_background", "pbn_oh", "pbn_ch3_dmso", "pbn_ooh_o2minus"],
    "M3_n2rr_candidate": [
        "ov_broad_background",
        "pbn_oh",
        "pbn_ch3_dmso",
        "pbn_ooh_o2minus",
        "pbn_nnh_candidate",
        "pbn_nh2_candidate",
    ],
    "M4_n2rr_extended": [
        "ov_broad_background",
        "pbn_oh",
        "pbn_ch3_dmso",
        "pbn_ooh_o2minus",
        "pbn_nnh_candidate",
        "pbn_nh2_candidate",
        "pbn_nhnh_candidate",
    ],
}

MODEL_DESCRIPTIONS: dict[str, str] = {
    "G0_single_line": "General one-component radical or unresolved singlet.",
    "G1_organic_radicals": "Carbon-centered, semiquinone/phenoxyl, and generic organic radical screening.",
    "G2_nitroxide_spin_label": "Common 14N/15N nitroxide and trityl/TAM-like spin-probe models.",
    "G3_ros_spin_trap_general": "General ROS/spin-trap screening without N2RR-specific assignments.",
    "G4_transition_metal_screen": "Approximate isotropic Cu(II), Mn(II), and V(IV)/vanadyl screening.",
    "G5_defect_plus_radical": "Broad defect envelope plus narrow radical components.",
    "M0_defect_only": "Pd-Ov-Bi2MoO6 oxygen-vacancy/trapped-electron background.",
    "M1_water_dmso": "PBN water/DMSO model with mandatory PBN-CH3 when PBN is introduced in DMSO.",
    "M2_water_dmso_o2": "PBN water/DMSO/O2 model including PBN-OOH/O2-derived adducts.",
    "M3_n2rr_candidate": "DMSO-corrected PBN model with N2RR-associated candidate components.",
    "M4_n2rr_extended": "Extended N2RR candidate model with higher overfitting risk.",
}


def components_for_preset(preset: str) -> list[SpinComponent]:
    library = default_components()
    return [library[cid].clone() for cid in MODEL_PRESETS[preset]]


def component_table() -> list[dict]:
    return [component.to_table_row() for component in default_components().values()]
